---
- name: Ec2 - Ansible Server - Launch
  ec2:
    key_name: "{{mykey}}"
    instance_type: "{{ec2_instance_type}}"
    image: "{{ec2_image}}"
    vpc_subnet_id: "{{ subnet_id }}"
    group_id: "{{ main_sg_id }}"
    assign_public_ip: True
    wait: true
    region: "{{aws_region}}"
    instance_tags: '{"Name":"{{ec2_ansible_Name}}","Environment":"{{ec2_tag_Environment}}"}'
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
  register: ec2
- name: See ec2 value
  debug: var=ec2
- name: Wait for Ansible Server SSH Service
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 120
  with_items: "{{ ec2.instances }}"
- name: Adding Ansible Server instance IP to host file
  copy:
    content: "[ansible]{{'\n'}}{{ item.public_ip }}"
    dest: /root/hosts
  with_items: "{{ ec2.instances }}"
